# Generated by Django 4.2.4 on 2023-09-06 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xmarks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="owner",
            new_name="user",
        ),
    ]
