# Generated by Django 4.2.4 on 2023-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='is_favorite',
            new_name='favorite',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='frequent',
            field=models.BooleanField(default=False),
        ),
    ]
